'use client';
import { createContext, useState, useContext } from 'react';

const translations = {
    es: {
        // Generales y Sidebar
        panelControl: "Panel de Control", puntoVenta: "Punto de Venta", inventario: "Inventario", 
        promociones: "Promociones", reportes: "Reportes", clientes: "Clientes", configuracion: "Configuración", 
        cerrarSesion: "Cerrar Sesión", enLinea: "En línea", sucursal: "Sucursal", todas: "Todas",
        // Módulo Ventas
        buscar: "BUSCAR", producto: "Producto", tipoPrecio: "Tipo Precio", unitario: "Unitario", 
        cantidadAbrev: "Cant.", importeNeto: "Importe Neto", esperandoLecturas: "Esperando lecturas...", 
        anadirRapido: "Añadir Rápido", verCatalogo: "Ver Catálogo Completo", subtotal: "Subtotal:", 
        descuentos: "Descuentos:", asignarPaciente: "Asignar Paciente:", publicoGeneral: "-- Público General --", 
        formaPago: "Forma de Pago:", efectivo: "Efectivo", tarjeta: "Tarjeta", transferencia: "Transferencia", total: "TOTAL:", 
        cobrar: "COBRAR", catalogoProductos: "Catálogo de Productos", buscarNombreCodigo: "🔍 Buscar por nombre o código...", 
        codigo: "Código", nombre: "Nombre", precio: "Precio", agregar: "Agregar", 
        registrarPaciente: "Registrar Paciente Rápido", nombreCompleto: "Nombre Completo", telefono: "Teléfono", 
        guardarSeleccionar: "Guardar y Seleccionar", cancelar: "Cancelar", 
        placeholderEscanear: "[Listo para escanear] Pasa el código de barras por el lector...", procesando: "PROCESANDO...", 
        carritoVacio: "Carrito vacío.", cobradoExito: "¡Cobrado con éxito en", general: "General", mayoreo: "Mayoreo", distribuidor: "Distribuidor", precioMedico: "Precio Médico",
        folioTransferencia: "Folio de Transferencia", ingresaFolio: "Ej. 987654321", debito: "Débito", credito: "Crédito", 
        tipoTarjeta: "Tipo de Tarjeta", historialDia: "Historial de Ventas del Día", vendedor: "Vendedor", hora: "Hora", 
        articulos: "Artículos", folioRequerido: "Debes ingresar el folio de la transferencia.", notasVentaOpcional: "Agregar Nota de Venta (Opcional)",
        // TRADUCCIONES MÓDULO FINANZAS
        // TRADUCCIONES MÓDULO FINANZAS (ACTUALIZADAS)
        // TRADUCCIONES COMPARATIVAS
        comparativasGrales: "Comparativas y Gráficos",
        tabSucursales: "Comparativa de Sucursales",
        tabDoctores: "Productividad Médica",
        comparativaSucursales: "Análisis Comparativo por Sucursal",
        sucursal: "Sucursal",
        totalVentas: "Total Ventas",
        consultas: "Consultas",
        productos: "Productos",
        ticketsTotales: "Tickets Emitidos",
        ticketPromedio: "Ticket Promedio",
        topProductos: "Top 3 Productos",
        comparativaDoctores: "Desempeño y Productividad por Doctor",
        doctor: "Doctor",
        consultasAtendidas: "Consultas Atendidas",
        ingresoGenerado: "Ingreso Generado",
        retencionPacientes: "Retención de Pacientes",
        indiceRetencion: "Índice Retención",
        pacientesUnicos: "Pacientes Únicos",
        sinDatosDoctores: "No hay consultas asignadas a doctores en este período.",
        sinDatosSucursales: "No hay ventas registradas en este período para comparar.",
        acupuntura: "Acupuntura",
        huanqiu: "Huanqiu",
        consultasAcupuntura: "Consultas (Acupuntura)",
        prodHuanqiu: "Productos (Huanqiu)",
        totalConsultasRealizadas: "Consultas Realizadas",
        subtotalEfectivo: "Subtotal Efectivo",
        subtotalTarjeta: "Subtotal Tarjeta",
        subtotalTransferencia: "Subtotal Transf.",
        ticketCorteAuditoria: "CORTE DE CAJA Y AUDITORÍA",
        detalleMovimientos: "DETALLE DE MOVIMIENTOS",
        firmaConformidad: "Firma de Conformidad",
        documentoAuditoria: "Documento de Auditoría",
        generadoAuto: "Generado automáticamente",
        ventaEfectivoAbrev: "Venta en Efectivo",
        movimientosFinanzas: "Reporte Financiero",
        reporteDiario: "Diario",
        reportePeriodo: "Período",
        vistaSucursal: "Sucursal",
        vistaGlobal: "Global",
        fechaGeneral: "Fecha General",
        desde: "Desde",
        hasta: "Hasta",
        exportarExcel: "Exportar Excel",
        imprimirReporte: "Imprimir Reporte",
        analizandoFinanzas: "Analizando finanzas...",
        cajaFisica: "Caja Física",
        enVivo: "EN VIVO",
        fondoInicial: "Fondo Inicial",
        ventasEfectivoAbrev: "Ventas (Efe)",
        entradas: "Entradas",
        salidas: "Salidas",
        fondoCajaBtn: "Fondo",
        entradaBtn: "Entrada",
        salidaBtn: "Salida",
        corteCajaBtn: "Corte",
        clinicaOficial: "Clínica Oficial",
        extrasProd: "Extras / Prod.",
        granTotalVentas: "Gran Total Ventas",
        efectivoLabel: "Efectivo",
        tarjetaLabel: "Tarjetas",
        transferenciaLabel: "Transfer.",
        efectivoTotal: "Efectivo Total",
        tarjetaTotal: "Tarjetas Total",
        transfTotal: "Transf. Total",
        tabConsultas: "Consultas",
        tabExtras: "Prod. y Extras",
        tabAuditoria: "Auditoría de Caja",
        folio: "Folio",
        fecha: "Fecha",
        sucursalEmisora: "Sucursal",
        clientes: "Cliente",
        servicioClinico: "Servicio Clínico",
        productoExtra: "Producto / Extra",
        cantidadAbrev: "Cant.",
        metPago: "Pago",
        importe: "Importe",
        sinDatosClinica: "No se encontraron ventas de clínica.",
        sinDatosExtras: "No se encontraron ventas extra.",
        fechaHoraCompleta: "Fecha y Hora",
        tipoMovimiento: "Movimiento",
        motivoDetalles: "Motivo / Detalles",
        ticketBtn: "Ticket",
        cierreTurnoAuditoria: "Cierre de Turno y Auditoría",
        detalleBtn: "Detalle",
        reimprimirBtn: "Reimprimir",
        sinDatosCaja: "No hay movimientos de caja registrados.",
        establecerFondoCaja: "Establecer Fondo de Caja",
        ingresoCajaTitulo: "Ingreso de Efectivo",
        retiroCajaTitulo: "Retiro de Efectivo",
        tipFondoCaja: "Tip: Si es para arrancar el turno, incluye la palabra 'Fondo' en el motivo.",
        montoEfectivoDesc: "Monto en Efectivo ($)",
        motivoDescripcion: "Motivo / Descripción",
        cancelar: "Cancelar",
        procesar: "Procesar",
        registrarBtn: "Registrar",
        alertaMontoInvalido: "Monto inválido.",
        alertaMotivoVacio: "Debes especificar un motivo.",
        alertaEfectivoInsuficiente: "No hay suficiente efectivo en caja para realizar este retiro.",
        alertaCajaCero: "La caja está en cero. No hay efectivo que cortar.",
        confirmarCorteLargo: "¿Realizar el Corte de Caja?\n\nEl sistema extraerá TODO el dinero del sistema dejándolo en $0.00 y se generará el ticket de auditoría.\n\n(Deberás ingresar el Fondo Inicial manualmente en tu próximo turno).",
        corteExitoso: "Corte de caja exitoso. La caja está ahora en $0.00.",
        reporteFinancieroDoc: "Reporte Financiero de Acupuntura HK",
        generadoAuto: "Generado automáticamente por el sistema",
        detallesTurnoPasado: "Detalles del Turno Pasado",
        fechaHoraCierre: "Fecha y Hora de Cierre",
        totalAuditado: "Total Auditado",
        transaccionesTurno: "Transacciones del Turno",
        noTransaccionesTurno: "No hubo transacciones registradas en este turno.",
        // Módulo Inventario
        catalogo: "Catálogo", familiasGrupos: "Familias / Grupos", kardex: "Kardex", nuevoProducto: "Nuevo Artículo", 
        familia: "Familia", stock: "Stock", ajustar: "Ajustar", suelto: "Suelto", familiasAgrupaciones: "Familias y Agrupaciones", 
        crearFamilia: "Crear Familia", id: "ID", nombreFamilia: "Nombre de Familia", accionesFamilia: "Acciones", 
        editarIntegrantes: "Editar Integrantes", fijarPrecioMasivo: "Fijar Precio Masivo", noFamiliasCreadas: "No has creado ninguna familia.", 
        kardexAuditoria: "Kardex de Auditoría", fecha: "Fecha", movimiento: "Movimiento", cantidad: "Cantidad", motivo: "Motivo", 
        editarFamilia: "Editar Familia", nuevaFamilia: "Nueva Familia", labelNombreFamilia: "Nombre de la Familia", 
        ejemploFamilia: "Ej. Agujas de Acero", seleccionaProductosFamilia: "Selecciona los productos que pertenecen a esta familia:", 
        guardarFamilia: "Guardar Familia", nuevoArticulo: "Nuevo Artículo", familiaOpcional: "Familia (Opcional)", 
        sinGrupo: "-- Sin Grupo (Suelto) --", codigoBarras: "Código de barras", nombreArticulo: "Nombre del artículo", 
        preciosInstruccion: "Precios (Deja blanco May/Dist/Médico para copiar General)", generalReq: "General *", guardarArticulo: "Guardar Artículo", 
        cantidadInvalida: "Cantidad no válida", stockActualizado: "Stock actualizado.", preciosInvalidos: "Precios inválidos.", 
        preciosActualizadosGlobal: "Precios actualizados en todas las sucursales.", promptPrecioMasivo1: "Ingresa el nuevo PRECIO GENERAL para todos los artículos de la familia", 
        promptPrecioMasivo2: "Los precios de mayoreo, distribuidor y médico se igualarán a este.", preciosMasivosAplicados: "Precios masivos aplicados correctamente a todos los integrantes de la familia.", 
        nombreFamiliaObligatorio: "El nombre de la familia es obligatorio.", faltanCampos: "Faltan campos obligatorios.", familiaGuardadaExito: "guardada exitosamente.",
        editar: "Editar", eliminar: "Eliminar", confirmarEliminarProducto: "¿Estás seguro de eliminar este artículo? Se ocultará del catálogo pero se mantendrá en el historial de reportes.",
        tipoArticulo: "Tipo de Artículo", productoFisico: "Producto Físico (Inventariable)", servicioInfinito: "Servicio (Stock Infinito)",
        infinito: "Infinito", productoEliminadoExito: "Artículo eliminado del catálogo.", productoActualizadoExito: "Artículo actualizado exitosamente.", editarArticulo: "Editar Artículo",
        inventarioGlobal: "Inventario Global", transferir: "Transferir", transferenciaInventario: "Transferencia de Inventario", 
        sucursalDestino: "Sucursal Destino", cantidadTransferir: "Cantidad a Transferir", motivoOpcional: "Motivo (Opcional)", 
        confirmarTransferencia: "Confirmar Transferencia", transferenciaExitosa: "Transferencia completada con éxito.", 
        errorTransferencia: "Error en la transferencia: ", seleccionaDestino: "Selecciona la sucursal destino.", 
        totalGlobal: "Total Global", exportarKardex: "Exportar Kardex (CSV)", imprimirPdf: "Imprimir PDF",
        estrategiaPrecio: "Estrategia de Precio", descPrecioSucursal: "Este producto usará precios distintos por sucursal.", descPrecioGlobal: "Mismo precio para todas las sucursales (Global).", 
        preciosDiferenciados: "📍 Precios diferenciados (Solo esta sucursal)", preciosGlobales: "🌎 Usar precios globales compartidos", 
        tooltipPrecioSucursal: "Precio Fijo en esta Sucursal", tooltipPrecioGlobal: "Precio Global Compartido", 
        ajusteStock: "Ajuste (+/-)", guardarRenglon: "Guardar Renglón", errorStockNegativo: "El ajuste resulta en un stock negativo.", 
        preciosActualizadosLocal: "Precios actualizados (Solo en esta sucursal)", cambiosGuardados: "Cambios guardados correctamente.", 
        placeholderAjuste: "+0 / -0", aplicaGlobal: "(Aplica a nivel Global)",
        buscarArticulo: "Buscar por nombre, código o familia...",
        esConsultaMedica: "Contabilizar como 'Consulta Médica' en Reportes",
        consultaMedicaBadge: "Consulta Médica",
        // Módulo Promociones
        llenaCampos: "Llena los campos obligatorios.", seleccionaProductoAlert: "Selecciona un producto.", seleccionaFamiliaAlert: "Selecciona una familia.", 
        errorCrear: "Error al crear: ", campanaLanzada: "Campaña lanzada exitosamente.", confirmarBajaCampana: "¿Deseas dar de baja esta campaña?", 
        panelPromociones: "Panel de Promociones", crearCampana: "Crear Campaña", campana: "Campaña", aplicaA: "Aplica a", 
        mecanica: "Mecánica", vigencia: "Vigencia", estado: "Estado", precioFijo: "Precio Fijo", lleva: "Lleva", 
        gratis: "Gratis", familiaDosPuntos: "Familia: ", productoDosPuntos: "Producto: ", vigente: "VIGENTE", 
        inactiva: "INACTIVA", nuevaPromocion: "Nueva Promoción", porProducto: "Por Producto", porFamilia: "Por Familia (Grupo)", 
        seleccionaProducto: "-- Selecciona el Producto --", seleccionaFamilia: "-- Selecciona la Familia --", 
        nombrePromocionEjemplo: "Nombre (Ej. 3x2 Agujas Acero)", esquemaDescuento: "Esquema de Descuento:", porcentaje: "Porcentaje (%)", 
        porVolumen: "Por Volumen (Ej. 3x2)", llevaTotal: "Lleva (Total uds.):", ej3: "Ej. 3", descuentaGratis: "Descuenta (Gratis):", 
        ej1: "Ej. 1", valorDescuento: "Valor del descuento", inicio: "Inicio:", fin: "Fin:", lanzarOferta: "Lanzar Oferta",
        // Módulo Reportes Avanzados
        noDatosExportar: "No hay datos en el rango seleccionado para exportar.", folio: "Folio", fechaHora: "Fecha / Hora", 
        sucursalEmisora: "Sucursal", montoCobrado: "Monto Cobrado", cierreCaja: "Cierre_Caja", fechaInicio: "Fecha Inicio:", 
        fechaFin: "Fecha Fin:", excelCsv: "Exportar a Excel", procesandoNube: "Procesando transacciones en la nube...", 
        ingresosTotales: "INGRESOS TOTALES", consultasTotales: "SERVICIOS TOTALES", insumosDesplazados: "PRODUCTOS DESPLAZADOS", 
        ticketPromedio: "TICKET PROMEDIO", finanzasSucursal: "Finanzas por Sucursal", napoles: "Nápoles", obrera: "Obrera", 
        pedregal: "Pedregal", top5Vendidos: "Top 5 Más Vendidos", detalle: "Detalle", uds: "uds", sinDatos: "Sin datos.", 
        auditoriaTransacciones: "Auditoría de Transacciones Recientes", noMovimientos: "No se detectaron movimientos en el rango cronológico seleccionado.", 
        articuloEliminado: "Artículo eliminado", desgloseFinanciero: "Desglose Financiero por Sucursal", ingresosConsultas: "Ingresos por Servicios", 
        ingresosProductos: "Ingresos por Productos", participacion: "Participación",
        reporteDiario: "Reporte Diario", reportePeriodo: "Por Periodo", vistaSucursal: "Mi Sucursal", vistaGlobal: "Global (Todas)",
        empresaA: "Consultas (Servicios)", empresaB: "Productos Adicionales (Inventario)", ingresosA: "INGRESOS CONSULTAS", ingresosB: "INGRESOS PRODUCTOS",
        buscarReporte: "Filtrar por paciente o artículo...", granTotal: "GRAN TOTAL", metPago: "Método Pago",
        efectivoLabel: "Efectivo:", tarjetaLabel: "Tarjeta:", transferenciaLabel: "Transferencia:",
        efectivoTotal: "Efectivo Total:", tarjetaTotal: "Tarjeta Total:", transfTotal: "Transf. Total:",
        resumenGlobal: "RESUMEN GLOBAL (AMBAS EMPRESAS)", granTotalLabel: "GRAN TOTAL:",
        totalEfectivo: "Total Efectivo:", totalTarjetas: "Total Tarjetas:", totalTransferencias: "Total Transferencias:",
        totalConsultas: "Total Consultas:", totalProductos: "Total Productos:",
        excelEfectivo: "> Efectivo:", excelTarjetas: "> Tarjetas:", excelTransferencias: "> Transferencias:",
        // Módulo Configuración y Usuarios
        gestionUsuariosPermisos: "Gestión de Usuarios y Permisos", registrarEmpleado: "Registrar Empleado", cargandoPersonal: "Cargando personal...", 
        empleado: "Empleado", rolPrincipal: "Rol Principal", clinica: "Clínica", permisosAccesoModulos: "Permisos de Acceso a Módulos (Vistas)", 
        activo: "Activo", suspendido: "Suspendido", recepcionista: "Recepcionista", gerente: "Gerente", adminGlobal: "Admin Global", 
        todasGlobal: "Todas (Global)", accesoRestringido: "Acceso Restringido", soloAdminConfig: "Solo los administradores pueden gestionar la configuración del sistema.", 
        altaNuevoEmpleado: "Alta de Nuevo Empleado", correoLogin: "Correo Electrónico (Para login)", contrasenaTemporal: "Contraseña Temporal", 
        rol: "Rol", clinicaAsignada: "Clínica Asignada", crearCuenta: "Crear Cuenta", errorCrearUsuario: "Error al crear usuario: ", 
        usuarioCreadoExito: "Usuario creado exitosamente. Por favor, vuelve a iniciar sesión como Admin.",
        errorActualizandoPermisos: "Error actualizando permisos: ",
        // Módulo Consumos Médicos y Terapeutas (NUEVAS LLAVES)
        insumosMedicos: "Insumos Médicos", registroConsumo: "Registro de Salidas", directorioDoctores: "Directorio Médico",
        reportesConsumo: "Reportes de Consumo", seleccionaDoctor: "-- Selecciona un Doctor --", registrarSalida: "REGISTRAR SALIDA",
        nuevoDoctor: "Nuevo Doctor", especialidad: "Especialidad", crearDoctor: "Registrar Médico",
        historialDoctores: "Historial de Consumo por Doctor", reporteMensual: "Reporte Mensual",
        articulosEntregados: "Artículos Entregados", consumoRegistrado: "Consumo registrado y descontado del inventario exitosamente.",
        stockInsuficiente: "¡Stock insuficiente! Solo quedan", unidadesDe: "unidades de", enLugar: "en", 
        codigoNoRegistrado: "Código no registrado en esta sucursal:", limiteAlcanzado: "Límite alcanzado: Solo hay", 
        disponibles: "disponibles.", atencion: "Atención: ", error: "Error: ", agregaInsumos: "Agrega insumos para registrar salida.",
        marcaEstrella: "Marca la estrella en el inventario para anclar insumos aquí.", disp: "Disp.", verCatalogoCompleto: "Ver Catálogo Completo",
        terapeutaAsignado: "Terapeuta Asignado", seleccionaQuienRetira: "Selecciona quién retira", accionDescontaraInventario: "Esta acción descontará el inventario en",
        noGeneraraIngresos: "pero no generará ingresos financieros.", directorioTerapeutas: "Directorio de Terapeutas", nuevoTerapeuta: "Nuevo Terapeuta",
        inactivo: "Inactivo", noDoctores: "No hay doctores registrados.", historialSalidas: "Historial de Salidas", filtrarTerapeuta: "Filtrar por Terapeuta",
        todosTerapeutas: "Todos los Terapeutas", materialRetirado: "Material Retirado", noSalidas: "No se encontraron salidas en este periodo.",
        registrarTerapeuta: "Registrar Terapeuta", ejAcupunturista: "Ej. Acupunturista", opcional: "Opcional", guardar: "Guardar",
        catalogoInsumos: "Catálogo de Insumos", anadir: "Añadir", noInsumo: "No se encontró el insumo.",
        // Módulo Caja
        flujoCaja: "Caja y Efectivo", saldoActual: "Efectivo en Caja", montoRecibido: "Efectivo Recibido:", 
        cambio: "Cambio a devolver", montoInsuficiente: "El monto recibido es menor al total a cobrar.",
        ingresarEfectivo: "Ingresar Efectivo", retirarEfectivo: "Retirar Efectivo", hacerCorte: "Hacer Corte de Caja",
        movimientosHoy: "Movimientos de Hoy", tipoMovimiento: "Tipo", ingresoManual: "Ingreso Manual",
        retiroManual: "Retiro Manual", ventaEfectivo: "Venta (Efectivo)", corteDeCaja: "Corte de Caja",
        motivo: "Motivo / Concepto", confirmarCorte: "¿Estás seguro de hacer el corte? Se retirará todo el efectivo y la caja quedará en $0.00",
        corteExitoso: "Corte de caja realizado exitosamente. Guarda el dinero.",
        cajaFinanzas: "Caja y Finanzas", consumosMedicos: "Consumos Médicos", promociones: "Promociones", cerrarSesion: "Cerrar Sesión",
        efectivoActualCaja: "Efectivo Actual en Caja",
        desgloseTurnoActual: "Desglose del Turno Actual",
        fondoCaja: "Fondo de caja",
        ventasEfectivoAbrev: "Ventas en Efectivo",
        entradasManuales: "Entradas Manuales",
        salidasRetiros: "Salidas / Retiros",
        totalEnCaja: "TOTAL EN CAJA",
        flujoFecha: "Flujo de la Fecha",
        entradaBtn: "Entrada",
        salidaBtn: "Salida",
        cerrarTurnoCortarCaja: "Cerrar Turno y Cortar Caja",
        actividadTurno: "Actividad del Turno",
        movimientos: "Movimientos",
        sinActividad: "Aún no hay actividad",
        sinActividadDesc: "Las ventas y movimientos aparecerán aquí.",
        historialAuditoriaGlobal: "Historial y Auditoría Global",
        buscarHistorial: "Buscar en el historial completo...",
        fechaHoraCompleta: "Fecha y Hora",
        tipoMovimiento: "Movimiento",
        motivoDetalles: "Motivo / Detalles",
        importe: "Importe",
        cierreTurnoAuditoria: "Cierre de Turno y Auditoría",
        detalleBtn: "Detalle",
        noRegistros: "No se encontraron registros.",
        detallesTurnoPasado: "Detalles del Turno Pasado",
        fechaHoraCierre: "Fecha y Hora de Cierre",
        totalAuditado: "Total Auditado",
        transaccionesTurno: "Transacciones del Turno",
        noTransaccionesTurno: "No hubo transacciones registradas en este turno.",
        ingresoCajaTitulo: "Ingreso a Caja",
        retiroCajaTitulo: "Retiro de Caja",
        tipFondoCaja: "Tip: Si es para arrancar el turno, incluye la palabra \"Fondo\" en el motivo.",
        registrarBtn: "Registrar",
        alertaMontoInvalido: "Monto inválido.",
        alertaMotivoVacio: "Debes especificar un motivo.",
        alertaEfectivoInsuficiente: "No hay suficiente efectivo en caja para realizar este retiro.",
        alertaCajaCero: "La caja está en cero.",
        confirmarCorteLargo: "¿Estás seguro de hacer el Corte de Caja?\n\nEl turno actual se cerrará, el dinero actual pasará a ser el Fondo de Caja del siguiente turno, los contadores volverán a cero y se imprimirá tu Ticket detallado.",
        corteGenerandoTicket: "Corte de caja registrado exitosamente. Generando ticket...",
        alertaCorteAntiguo: "Este corte es muy antiguo y no posee el formato compatible para visualizar el desglose.",
        alertaErrorTicket: "No se pudo generar el ticket.",
        fondoInicial: "Fondo Inicial",
        entradas: "Entradas",
        salidas: "Salidas",
        cortesCaja: "Cortes de Caja",
        totalAlCierre: "Total al cierre",
        detalleMovimientos: "DETALLE DE MOVIMIENTOS",
        ticketCorteTitulo: "Ticket de Corte",
        corteCajaTurno: "CORTE DE CAJA (TURNO)",
        firmaConformidad: "Firma de Conformidad",
        documentoAuditoria: "Documento de Auditoría",
        generadoAuto: "Generado automáticamente",
        // Módulo Clientes y Expedientes
        directorioExpedientes: "Expedientes Clínicos (Admisión)", placeholderBuscarCliente: "🔍 Buscar por nombre, teléfono, CURP o expediente...", 
        nuevoPaciente: "Nuevo Paciente", expediente: "Expediente", datosGenerales: "Datos Personales",
        sexo: "Sexo", curp: "CURP", sinCurp: "Motivo sin CURP", fechaNacimiento: "Fecha de Nacimiento",
        correo: "Correo Electrónico", domicilio: "Domicilio Completo", contactoEmergencia: "Contacto de Emergencia",
        parentesco: "Parentesco", responsableLegal: "Responsable Legal (Si aplica)", idioma: "Idioma Preferente",
        alertasClinicas: "Alertas Clínicas", tipoAlerta: "Tipo de Alerta", descripcionAlerta: "Descripción", gravedad: "Gravedad",
        alergia: "Alergia", embarazo: "Embarazo", marcapasos: "Marcapasos/Implante", anticoagulantes: "Anticoagulantes",
        enfermedadTransmisible: "Enfermedad Transmisible", riesgoUrgencia: "Riesgo/Urgencia",
        altaPacienteExito: "Expediente creado exitosamente.", camposObligatorios: "Faltan campos obligatorios.",
        visitas: "Visitas", totalInvertido: "Total Invertido", acciones: "Acciones", verHistorialCompleto: "Ver Historial Completo", 
        sinTelefono: "Sin teléfono", articulo: "Artículo", pUnit: "P. Unit", totalTicket: "Total Ticket:", sinRegistrosCompras: "No hay registros de compras.",
        estadoCivil: "Estado Civil", soltero: "Soltero(a)", casado: "Casado(a)", divorciado: "Divorciado(a)", viudo: "Viudo(a)", unionLibre: "Unión Libre", otro: "Otro", ocupacion: "Ocupación", ejOcupacion: "Ej. Estudiante, Docente, Ing...", pacienteHablaIngles: "Paciente habla Inglés (Pase directo con Médico)", notaInterna: "Nota Interna (Staff)", notaInternaDesc: "Comentarios privados. El paciente no verá esto.", ejNotaInterna: "Ej. Cliente conflictivo, prefiere pasar con la Dra. Ana...", abandonoTx: "Abandono de Tx", alDia: "Al Día", confirmarEliminarExpediente: "¿Estás seguro de que deseas eliminar permanentemente el expediente de", accionNoDeshacer: "Esta acción no se puede deshacer.", expedienteEliminadoExito: "Expediente duplicado eliminado correctamente.", errorEliminarExpediente: "Error al eliminar: Es probable que este paciente ya tenga ventas o historial clínico asociado y no pueda borrarse por seguridad. \n\nDetalle: ", descAlertasClinicas: "Estas alertas generarán un bloqueo visual rojo en el historial del paciente.", seleccionarAlerta: "-- Seleccionar Alerta --", especificarDetalleAlerta: "Especificar detalle de la alerta...", anadirAlerta: "Añadir Alerta", guardarExpediente: "Guardar Expediente", editarExpediente: "Editar Expediente", altaExpedienteClinico: "Alta de Expediente Clínico", expAbrev: "Exp:", sinCurpAbrev: "Sin CURP", noExpedientes: "No se encontraron expedientes.", inactivoPor: "Inactivo por", dias: "días", anos: "años", pacienteYaExiste: "Parece que este paciente ya existe", confirmarCrearNuevo: "¿Estás seguro de crear un registro nuevo?", errorActualizar: "Error al actualizar: ", seleccionar: "Seleccionar", femenino: "Femenino", masculino: "Masculino", contactoEmergenciaNum: "Contacto de Emergencia",
        // Módulo Escritorio Médico
        escritorioMedico: "Escritorio Médico", historiaClinica: "Historia Clínica", notasEvolucion: "Notas de Evolución", 
        motivoConsulta: "Motivo de Consulta", padecimientoActual: "Padecimiento Actual", antecedentesFamiliares: "Antecedentes Familiares", 
        antecedentesPersonales: "Antecedentes Personales (Patológicos)", habitosSustancias: "Hábitos y Uso de Sustancias", 
        medicamentosActuales: "Medicamentos Actuales", ginecoObstetricos: "Antecedentes Gineco-Obstétricos", 
        interrogatorioSistemas: "Interrogatorio por Aparatos y Sistemas", exploracionFisica: "Exploración Física y Signos Vitales", 
        diagnosticoCie: "Diagnóstico (CIE) / Problema Clínico", valoracionMtc: "Valoración MTC (Síndrome/Patrón)", 
        pronostico: "Pronóstico", planTratamiento: "Plan de Tratamiento / Objetivos", firmar: "Firmar y Cerrar Documento", 
        documentoFirmado: "Documento Firmado e Inalterable", evolucion: "Evolución (Cambios, dolor)", 
        evaluacionSignos: "Evaluación y Signos", procedimientoTecnica: "Procedimiento (Puntos, técnica)", 
        materialAgujas: "Material (Agujas, estériles, marcas)", resultadoTolerancia: "Resultado y Tolerancia", 
        planIndicaciones: "Plan e Indicaciones", nuevaNota: "Nueva Nota de Evolución", guardarBorrador: "Guardar Borrador",
        consentimientos: "Consentimientos Informados", adendas: "Adendas (Correcciones)", nuevoConsentimiento: "Generar Consentimiento",
        testigo1: "Nombre Completo Testigo 1", testigo2: "Nombre Completo Testigo 2", pacienteAcepta: "El paciente comprende los riesgos y acepta el tratamiento.",
        exportarPdf: "Exportar Expediente Oficial (PDF)", textoLegalAcupuntura: "Autorizo a Acupuntura China Tradicional HK a realizarme los procedimientos de acupuntura humana, electroacupuntura, ventosas y afines. Entiendo los beneficios y riesgos (dolor leve, hematoma, mareo).",
        firmarConsentimiento: "Firmar Consentimiento Oficial", redactarAdenda: "Redactar Adenda (Corrección)", firmarAdenda: "Firmar Adenda",
        avisoPrivacidad: "Aceptó Aviso de Privacidad (v1.0)", aceptarAviso: "Obligatorio: El paciente debe aceptar el Aviso de Privacidad.",
        hojaReferencia: "Generar Hoja de Referencia (Traslado)", motivoTraslado: "Motivo de Traslado / Urgencia",
        hospitalReceptor: "Establecimiento Receptor", impresionDiagnostica: "Impresión Diagnóstica Actual",
        // Claves faltantes - Módulo Escritorio Médico
        misPacientes: "Mis Pacientes",
        buscarPaciente: "Buscar paciente...",
        noResultados: "No se encontraron resultados.",
        interrogatorio: "Interrogatorio",
        antecedentesHabitos: "Antecedentes y Hábitos",
        planificacionFamiliar: "Métodos de Planificación Familiar",
        antecedentesRenalesPsicologicos: "Antecedentes Renales y Psicológicos",
        esferaFisicaMental: "Esfera Física y Mental",
        esferaMental: "Esfera Mental (TDAH, Estrés, Depresión...)",
        habitosSueno: "Hábitos de Sueño (¿Cómo duerme?)",
        diagnosticoMtc: "Diagnóstico MTC (Medicina Tradicional China)",
        mtcPulsoLengua: "Pulso y Lengua",
        mtcRostroOjos: "Rostro y Ojos",
        mtcColoresSaboresSonidos: "Colores, Sabores y Sonidos",
        conclusionTratamiento: "Conclusión y Tratamiento",

        imprimirDiagnostico: "Imprimir Diagnóstico",
        resumenSesionImpresion: "Resumen de Sesión (Para Impresión)",
        puntosAcupuntura: "Puntos de Acupuntura Utilizados",
        tiempoRetencion: "Tiempo de Retención (Minutos)",
        sesionesRequeridas: "Sesiones Requeridas (Sugeridas)",
        diagnosticoSesion: "Diagnóstico de la Sesión (Dictamen)",

        alertaFaltanCamposHistoria: "Para firmar, debes llenar al menos el Motivo, Diagnóstico y Plan.",
        confirmarFirmaHistoria: "¿Estás seguro de firmar? El documento quedará bloqueado e inalterable por ley.",
        borradorGuardado: "Borrador Guardado",
        normaFirmaNota: "Por norma, no puedes firmar con campos vacíos. Describe la evolución, el procedimiento o el diagnóstico de la sesión.",
        confirmarFirmaNota: "¿Estás seguro de firmar esta nota? No podrá ser borrada ni alterada.",
        alertaSinDiagnostico: "No hay un diagnóstico de sesión escrito para imprimir.",

        alertaCamposMinimos: "Nombre, Teléfono, Fecha de Nacimiento y Sexo son obligatorios.",
        errorRegistrar: "Error al registrar: ",
        expedienteCreadoExito: "Expediente creado exitosamente.",

        alertaAdendaCorta: "La adenda debe ser clara y justificada.",
        confirmarFirmaAdenda: "¿Firmar y anexar esta adenda al expediente?",
        adendaFirmadaExito: "Adenda firmada y anexada exitosamente.",

        alertaTestigos: "Se requieren los nombres de dos testigos legales.",
        alertaAceptarTerminos: "El paciente debe aceptar los términos marcando la casilla.",
        confirmarConsentimientoLegal: "Al firmar, el consentimiento será registrado legalmente a nombre del paciente y testigos.",
        consentimientoGeneradoExito: "Consentimiento oficial generado y firmado.",

        alertaDatosTraslado: "Debes llenar todos los datos de traslado.",

        seleccionarOCrearNota: "Selecciona o crea una nota",
        historialEvolucionClinica: "El historial de evolución clínica aparecerá aquí.",

        consentimientosVacios: "No hay consentimientos registrados en este expediente.",
        consentimientoOficial: "Consentimiento Oficial",

        escritorioClinico: "Escritorio Clínico",
        seleccionarPacienteDirectorio: "Selecciona un paciente del directorio lateral para comenzar.",

        altaRapida: "Alta Rápida",
        camposMinimosNorma: "Campos mínimos requeridos por norma. Recepción puede completar el resto después.",
        nombreCompleto: "Nombre Completo",
        telefono: "Teléfono",
        fechaNacimiento: "Fecha de Nacimiento",
        sexo: "Sexo",
        crearExpediente: "Crear Expediente",

        generarHojaReferencia: "Generar Hoja de Referencia",
        documentoReferenciaDescripcion: "Este documento oficial ampara el traslado o envío del paciente a otro hospital para urgencias o estudios.",
        generarDocumento: "Generar Documento",

        imprimirRecetaDiagnostico: "Imprimir Receta/Diagnóstico para el paciente",
        escribeCorreccion: "Escribe la fe de erratas o corrección aquí...",
        firmadaPor: "Firmada por",
        cancelar: "Cancelar",

        // PDF - Dictamen
        dictamenEvaluacionSeguimiento: "Dictamen de Evaluación y Seguimiento",
        paciente: "Paciente:",
        fecha: "Fecha:",
        expediente: "Expediente:",
        terapeuta: "Terapeuta:",
        diagnosticoEvaluacionClinica: "Diagnóstico / Evaluación Clínica:",
        pronosticoTratamientoSugerido: "Pronóstico y Tratamiento Sugerido:",
        sesionesSeguimiento: "Se recomiendan",
        sesionesParaObservarEvolucion: "sesiones de seguimiento para observar evolución.",
        indicacionesCasa: "Indicaciones para Casa:",
        firmaTerapeuta: "Firma del Terapeuta",

        // PDF - Expediente
        expedienteClinico: "Expediente Clínico",
        expedienteClinicoOficial: "Expediente Clínico Oficial (Cumplimiento NOM-004-SSA3-2012)",
        identificacionPaciente: "IDENTIFICACIÓN DEL PACIENTE",
        nombre: "Nombre:",
        curp: "CURP:",
        noProporcionado: "No proporcionado",
        sexoTelefono: "Sexo / Teléfono:",
        alertasClinicas: "ALERTAS CLÍNICAS",
        historiaClinicaInicial: "HISTORIA CLÍNICA INICIAL",
        motivoConsultaPdf: "Motivo Consulta:",
        diagnosticoCiePdf: "Diagnóstico (CIE):",
        planTratamientoPdf: "Plan de Tratamiento:",
        firmadoPor: "FIRMADO POR:",

        // PDF - Referencia
        hojaReferenciaTrasladoMedico: "HOJA DE REFERENCIA Y TRASLADO MÉDICO",
        establecimientoReceptorPdf: "Establecimiento Receptor:",
        fechaHoraEmision: "Fecha y Hora de Emisión:",
        datosPaciente: "DATOS DEL PACIENTE",
        nombrePaciente: "Nombre del Paciente:",
        expedienteCurp: "Expediente Clínico / CURP:",
        edadSexo: "Edad / Sexo:",
        resumenClinicoMotivoEnvio: "RESUMEN CLÍNICO Y MOTIVO DE ENVÍO",
        impresionDiagnosticaPdf: "Impresión Diagnóstica:",
        motivoReferenciaUrgencia: "Motivo de Referencia / Urgencia:",
        medicoTratante: "Médico Tratante",
        nombreFirmaMedico: "Nombre y Firma del Médico",
    },
    en: {
        // Generales y Sidebar
        panelControl: "Control Panel", puntoVenta: "Point of Sale", inventario: "Inventory", 
        promociones: "Promotions", reportes: "Reports", clientes: "Customers", configuracion: "Settings", 
        cerrarSesion: "Logout", enLinea: "Online", sucursal: "Branch", todas: "All",
        // Módulo Ventas
        buscar: "SEARCH", producto: "Product", tipoPrecio: "Price Type", unitario: "Unit", 
        cantidadAbrev: "Qty.", importeNeto: "Net Amount", esperandoLecturas: "Waiting for scans...", 
        anadirRapido: "Quick Add", verCatalogo: "View Full Catalog", subtotal: "Subtotal:", 
        descuentos: "Discounts:", asignarPaciente: "Assign Patient:", publicoGeneral: "-- General Public --", 
        formaPago: "Payment Method:", efectivo: "Cash", tarjeta: "Card", transferencia: "Transfer", total: "TOTAL:", 
        cobrar: "CHARGE", catalogoProductos: "Product Catalog", buscarNombreCodigo: "🔍 Search by name or code...", 
        codigo: "Code", nombre: "Name", precio: "Price", agregar: "Add", 
        registrarPaciente: "Quick Register Patient", nombreCompleto: "Full Name", telefono: "Phone", 
        guardarSeleccionar: "Save & Select", cancelar: "Cancel", 
        placeholderEscanear: "[Ready to scan] Swipe barcode...", procesando: "PROCESSING...", 
        carritoVacio: "Empty cart.", cobradoExito: "Successfully charged in", general: "General", mayoreo: "Wholesale", distribuidor: "Distributor", precioMedico: "Medical Price",
        folioTransferencia: "Transfer Ref No.", ingresaFolio: "E.g. 987654321", debito: "Debit", credito: "Credit", 
        tipoTarjeta: "Card Type", historialDia: "Today's Sales History", vendedor: "Cashier", hora: "Time", 
        articulos: "Items", folioRequerido: "You must enter the transfer reference number.",
        cajaFinanzas: "Cash & Finances", consumosMedicos: "Medical Supplies", promociones: "Promotions", cerrarSesion: "Log Out", notasVentaOpcional: "Add Sales Note (Optional)",
        // TRADUCCIONES MÓDULO FINANZAS
        comparativasGrales: "Comparatives and Charts",
        tabSucursales: "Branch Comparison",
        tabDoctores: "Medical Productivity",
        comparativaSucursales: "Comparative Analysis by Branch",
        sucursal: "Branch",
        totalVentas: "Total Sales",
        consultas: "Consultations",
        productos: "Products",
        ticketsTotales: "Tickets Issued",
        ticketPromedio: "Average Ticket",
        topProductos: "Top 3 Products",
        comparativaDoctores: "Doctor Performance & Productivity",
        doctor: "Doctor",
        consultasAtendidas: "Consultations Attended",
        ingresoGenerado: "Revenue Generated",
        retencionPacientes: "Patient Retention",
        indiceRetencion: "Retention Rate",
        pacientesUnicos: "Unique Patients",
        sinDatosDoctores: "No consultations assigned to doctors in this period.",
        sinDatosSucursales: "No sales recorded in this period for comparison.",
        acupuntura: "Acupuncture",
        huanqiu: "Huanqiu",
        consultasAcupuntura: "Consultations (Acupuncture)",
        prodHuanqiu: "Products (Huanqiu)",
        totalConsultasRealizadas: "Consultations Performed",
        subtotalEfectivo: "Cash Subtotal",
        subtotalTarjeta: "Card Subtotal",
        subtotalTransferencia: "Transfer Subtotal",
        ticketCorteAuditoria: "CASH RECONCILIATION & AUDIT",
        detalleMovimientos: "MOVEMENT DETAILS",
        firmaConformidad: "Acknowledgment Signature",
        documentoAuditoria: "Audit Document",
        generadoAuto: "Automatically generated",
        ventaEfectivoAbrev: "Cash Sale",
        movimientosFinanzas: "Financial Report",
        reporteDiario: "Daily",
        reportePeriodo: "Period",
        vistaSucursal: "Branch View",
        vistaGlobal: "Global View",
        fechaGeneral: "General Date",
        desde: "From",
        hasta: "To",
        exportarExcel: "Export to Excel",
        imprimirReporte: "Print Report",
        analizandoFinanzas: "Analyzing finances...",
        cajaFisica: "Physical Cash Drawer",
        enVivo: "LIVE",
        fondoInicial: "Initial Float",
        ventasEfectivoAbrev: "Cash Sales (Cash)",
        entradas: "Inflows",
        salidas: "Outflows",
        fondoCajaBtn: "Float",
        entradaBtn: "Cash In",
        salidaBtn: "Cash Out",
        corteCajaBtn: "Reconcile",
        clinicaOficial: "Official Clinic",
        extrasProd: "Extras / Prod.",
        granTotalVentas: "Grand Total Sales",
        efectivoLabel: "Cash",
        tarjetaLabel: "Cards",
        transferenciaLabel: "Transfer",
        efectivoTotal: "Total Cash",
        tarjetaTotal: "Total Cards",
        transfTotal: "Total Transfer",
        tabConsultas: "Consultations",
        tabExtras: "Products & Extras",
        tabAuditoria: "Cash Audit",
        folio: "Folio",
        fecha: "Date",
        sucursalEmisora: "Branch",
        clientes: "Client",
        servicioClinico: "Clinical Service",
        productoExtra: "Product / Extra",
        cantidadAbrev: "Qty.",
        metPago: "Payment",
        importe: "Amount",
        sinDatosClinica: "No clinic sales found.",
        sinDatosExtras: "No extra sales found.",
        fechaHoraCompleta: "Date & Time",
        tipoMovimiento: "Type",
        motivoDetalles: "Reason / Details",
        ticketBtn: "Ticket",
        cierreTurnoAuditoria: "Shift Closure & Audit",
        detalleBtn: "Details",
        reimprimirBtn: "Reprint",
        sinDatosCaja: "No cash register movements recorded.",
        establecerFondoCaja: "Set Cash Float",
        ingresoCajaTitulo: "Cash Deposit",
        retiroCajaTitulo: "Cash Withdrawal",
        tipFondoCaja: "Tip: If it's to start the shift, include the word 'Float' in the reason.",
        montoEfectivoDesc: "Cash Amount ($)",
        motivoDescripcion: "Reason / Description",
        cancelar: "Cancel",
        procesar: "Process",
        registrarBtn: "Register",
        alertaMontoInvalido: "Invalid amount.",
        alertaMotivoVacio: "You must specify a reason.",
        alertaEfectivoInsuficiente: "Insufficient cash in drawer for this withdrawal.",
        alertaCajaCero: "The cash drawer is at zero. No cash to reconcile.",
        confirmarCorteLargo: "Perform Cash Reconciliation?\n\nThe system will withdraw ALL the money from the drawer, leaving it at $0.00, and the audit ticket will be generated.\n\n(You must manually enter the Initial Float for your next shift).",
        corteExitoso: "Cash reconciliation successful. The cash drawer is now at $0.00.",
        reporteFinancieroDoc: "HK Acupuncture Financial Report",
        generadoAuto: "Automatically generated by the system",
        detallesTurnoPasado: "Past Shift Details",
        fechaHoraCierre: "Closing Date & Time",
        totalAuditado: "Audited Total",
        transaccionesTurno: "Shift Transactions",
        noTransaccionesTurno: "No transactions were recorded in this shift.",
        // Módulo Inventario
        catalogo: "Catalog", familiasGrupos: "Families / Groups", kardex: "Kardex", nuevoProducto: "New Item", 
        familia: "Family", stock: "Stock", ajustar: "Adjust", suelto: "Single", familiasAgrupaciones: "Families & Groups", 
        crearFamilia: "Create Family", id: "ID", nombreFamilia: "Family Name", accionesFamilia: "Actions", 
        editarIntegrantes: "Edit Members", fijarPrecioMasivo: "Set Mass Price", noFamiliasCreadas: "No families created yet.", 
        kardexAuditoria: "Audit Kardex", fecha: "Date", movimiento: "Movement", cantidad: "Quantity", motivo: "Reason", 
        editarFamilia: "Edit Family", nuevaFamilia: "New Family", labelNombreFamilia: "Family Name", 
        ejemploFamilia: "E.g. Steel Needles", seleccionaProductosFamilia: "Select products that belong to this family:", 
        guardarFamilia: "Save Family", nuevoArticulo: "New Item", familiaOpcional: "Family (Optional)", 
        sinGrupo: "-- No Group (Single) --", codigoBarras: "Barcode", nombreArticulo: "Item Name", 
        preciosInstruccion: "Prices (Leave blank to copy General)", generalReq: "General *", guardarArticulo: "Save Item", 
        cantidadInvalida: "Invalid quantity", stockActualizado: "Stock updated.", preciosInvalidos: "Invalid prices.", 
        preciosActualizadosGlobal: "Prices updated in all branches.", promptPrecioMasivo1: "Enter the new GENERAL PRICE for all items in the family", 
        promptPrecioMasivo2: "Wholesale, distributor, and medical prices will match this.", preciosMasivosAplicados: "Mass prices successfully applied to all family members.", 
        nombreFamiliaObligatorio: "Family name is required.", faltanCampos: "Missing required fields.", familiaGuardadaExito: "successfully saved.",
        editar: "Edit", eliminar: "Delete", confirmarEliminarProducto: "Are you sure you want to delete this item? It will be hidden from the catalog but kept in reports history.",
        tipoArticulo: "Item Type", productoFisico: "Physical Product (Uses Stock)", servicioInfinito: "Service (Infinite Stock)",
        infinito: "Infinite", productoEliminadoExito: "Item removed from catalog.", productoActualizadoExito: "Item successfully updated.", editarArticulo: "Edit Item",
        inventarioGlobal: "Global Inventory", transferir: "Transfer", transferenciaInventario: "Inventory Transfer", 
        sucursalDestino: "Destination Branch", cantidadTransferir: "Transfer Quantity", motivoOpcional: "Reason (Optional)", 
        confirmarTransferencia: "Confirm Transfer", transferenciaExitosa: "Transfer successfully completed.", 
        errorTransferencia: "Transfer error: ", seleccionaDestino: "Select a destination branch.", 
        totalGlobal: "Global Total", exportarKardex: "Export Kardex (CSV)", imprimirPdf: "Print PDF",
        estrategiaPrecio: "Pricing Strategy", descPrecioSucursal: "This product will use different prices per branch.", descPrecioGlobal: "Same price for all branches (Global).", 
        preciosDiferenciados: "📍 Differentiated prices (Only this branch)", preciosGlobales: "🌎 Use shared global prices", 
        tooltipPrecioSucursal: "Fixed Price in this Branch", tooltipPrecioGlobal: "Shared Global Price", 
        ajusteStock: "Adjust (+/-)", guardarRenglon: "Save Row", errorStockNegativo: "Adjustment results in negative stock.", 
        preciosActualizadosLocal: "Prices updated (Only this branch)", cambiosGuardados: "Changes saved successfully.", 
        placeholderAjuste: "+0 / -0", aplicaGlobal: "(Applies globally)",
        buscarArticulo: "Search by name, code or family...",
        esConsultaMedica: "Count as 'Medical Consultation' in Reports",
        consultaMedicaBadge: "Medical Consultation",
        // Módulo Promociones
        llenaCampos: "Fill in the required fields.", seleccionaProductoAlert: "Select a product.", seleccionaFamiliaAlert: "Select a family.", 
        errorCrear: "Error creating: ", campanaLanzada: "Campaign launched successfully.", confirmarBajaCampana: "Do you want to deactivate this campaign?", 
        panelPromociones: "Promotions Panel", crearCampana: "Create Campaign", campana: "Campaign", aplicaA: "Applies to", 
        mecanica: "Mechanic", vigencia: "Validity", estado: "Status", precioFijo: "Fixed Price", lleva: "Buy", 
        gratis: "Free", familiaDosPuntos: "Family: ", productoDosPuntos: "Product: ", vigente: "ACTIVE", 
        inactiva: "INACTIVE", nuevaPromocion: "New Promotion", porProducto: "By Product", porFamilia: "By Family (Group)", 
        seleccionaProducto: "-- Select Product --", seleccionaFamilia: "-- Select Family --", 
        nombrePromocionEjemplo: "Name (E.g. Buy 2 Get 1 Steel Needles)", esquemaDescuento: "Discount Scheme:", porcentaje: "Percentage (%)", 
        porVolumen: "By Volume (E.g. Buy 2 Get 1 Free)", llevaTotal: "Buy (Total units):", ej3: "E.g. 3", descuentaGratis: "Discount (Free):", 
        ej1: "E.g. 1", valorDescuento: "Discount value", inicio: "Start:", fin: "End:", lanzarOferta: "Launch Offer",
        // Módulo Reportes Avanzados
        noDatosExportar: "No data in the selected range to export.", folio: "Invoice", fechaHora: "Date / Time", 
        sucursalEmisora: "Branch", montoCobrado: "Amount Charged", cierreCaja: "Register_Close", fechaInicio: "Start Date:", 
        fechaFin: "End Date:", excelCsv: "Export to Excel", procesandoNube: "Processing transactions in the cloud...", 
        ingresosTotales: "TOTAL REVENUE", consultasTotales: "TOTAL SERVICES", insumosDesplazados: "ITEMS SOLD", 
        ticketPromedio: "AVERAGE TICKET", finanzasSucursal: "Finances by Branch", napoles: "Napoles", obrera: "Obrera", 
        pedregal: "Pedregal", top5Vendidos: "Top 5 Best Sellers", detalle: "Detail", uds: "units", sinDatos: "No data.", 
        auditoriaTransacciones: "Recent Transactions Audit", noMovimientos: "No movements detected in the selected chronological range.", 
        articuloEliminado: "Deleted item", desgloseFinanciero: "Financial Breakdown by Branch", ingresosConsultas: "Service Revenue", 
        ingresosProductos: "Product Revenue", participacion: "Share",
        reporteDiario: "Daily Report", reportePeriodo: "By Period", vistaSucursal: "My Branch", vistaGlobal: "Global (All)",
        empresaA: "Consultations (Services)", empresaB: "Additional Products (Inventory)", ingresosA: "CONSULTATION REVENUE", ingresosB: "PRODUCT REVENUE",
        buscarReporte: "Filter by patient or item...", granTotal: "GRAND TOTAL", metPago: "Payment Method",
        efectivoLabel: "Cash:", tarjetaLabel: "Card:", transferenciaLabel: "Transfer:",
        efectivoTotal: "Total Cash:", tarjetaTotal: "Total Card:", transfTotal: "Total Transf.:",
        resumenGlobal: "GLOBAL SUMMARY (BOTH COMPANIES)", granTotalLabel: "GRAND TOTAL:",
        totalEfectivo: "Total Cash:", totalTarjetas: "Total Cards:", totalTransferencias: "Total Transfers:",
        totalConsultas: "Total Consultations:", totalProductos: "Total Products:",
        excelEfectivo: "> Cash:", excelTarjetas: "> Cards:", excelTransferencias: "> Transfers:",
        // Módulo Configuración y Usuarios
        gestionUsuariosPermisos: "User & Permissions Management", registrarEmpleado: "Register Employee", cargandoPersonal: "Loading staff...", 
        empleado: "Employee", rolPrincipal: "Main Role", clinica: "Clinic", permisosAccesoModulos: "Module Access Permissions (Views)", 
        activo: "Active", suspendido: "Suspended", recepcionista: "Receptionist", gerente: "Manager", adminGlobal: "Global Admin", 
        todasGlobal: "All (Global)", accesoRestringido: "Restricted Access", soloAdminConfig: "Only administrators can manage system settings.", 
        altaNuevoEmpleado: "New Employee Registration", correoLogin: "Email (For login)", contrasenaTemporal: "Temporary Password", 
        rol: "Role", clinicaAsignada: "Assigned Clinic", crearCuenta: "Create Account", errorCrearUsuario: "Error creating user: ", 
        usuarioCreadoExito: "User successfully created. Please log back in as Admin.",
        errorActualizandoPermisos: "Error updating permissions: ",
        // Módulo Consumos Médicos y Terapeutas (NUEVAS LLAVES)
        insumosMedicos: "Medical Supplies", registroConsumo: "Issue Supplies", directorioDoctores: "Medical Directory",
        reportesConsumo: "Consumption Reports", seleccionaDoctor: "-- Select a Doctor --", registrarSalida: "ISSUE SUPPLIES",
        nuevoDoctor: "New Doctor", especialidad: "Specialty", crearDoctor: "Register Doctor",
        historialDoctores: "Doctor Consumption History", reporteMensual: "Monthly Report",
        articulosEntregados: "Items Delivered", consumoRegistrado: "Supplies issued and inventory deducted successfully.",
        stockInsuficiente: "Insufficient stock! Only", unidadesDe: "units of", enLugar: "in", 
        codigoNoRegistrado: "Code not registered in this branch:", limiteAlcanzado: "Limit reached: Only", 
        disponibles: "available.", atencion: "Attention: ", error: "Error: ", agregaInsumos: "Add supplies to register issue.",
        marcaEstrella: "Mark the star in inventory to pin supplies here.", disp: "Avail.", verCatalogoCompleto: "View Full Catalog",
        terapeutaAsignado: "Assigned Therapist", seleccionaQuienRetira: "Select who is withdrawing", accionDescontaraInventario: "This action will deduct inventory in",
        noGeneraraIngresos: "but will not generate financial revenue.", directorioTerapeutas: "Therapist Directory", nuevoTerapeuta: "New Therapist",
        inactivo: "Inactive", noDoctores: "No doctors registered.", historialSalidas: "Issue History", filtrarTerapeuta: "Filter by Therapist",
        todosTerapeutas: "All Therapists", materialRetirado: "Withdrawn Material", noSalidas: "No issues found in this period.",
        registrarTerapeuta: "Register Therapist", ejAcupunturista: "E.g. Acupuncturist", opcional: "Optional", guardar: "Save",
        catalogoInsumos: "Supplies Catalog", anadir: "Add", noInsumo: "Supply not found.",
        // Módulo Caja
        flujoCaja: "Cash Register", saldoActual: "Cash in Register", montoRecibido: "Cash Tendered:", 
        cambio: "Change due", montoInsuficiente: "The amount received is less than the total due.",
        ingresarEfectivo: "Cash In", retirarEfectivo: "Cash Out", hacerCorte: "Close Register (Z-Report)",
        movimientosHoy: "Today's Movements", tipoMovimiento: "Type", ingresoManual: "Manual In",
        retiroManual: "Manual Out", ventaEfectivo: "Sale (Cash)", corteDeCaja: "Register Cut",
        motivo: "Reason / Concept", confirmarCorte: "Are you sure you want to close the register? All cash will be withdrawn and set to $0.00",
        corteExitoso: "Register successfully closed. Please secure the cash.",
        efectivoActualCaja: "Current Cash in Drawer",
        desgloseTurnoActual: "Current Shift Breakdown",
        fondoCaja: "Cash Float",
        ventasEfectivoAbrev: "Cash Sales",
        entradasManuales: "Manual Entries",
        salidasRetiros: "Outflows / Withdrawals",
        totalEnCaja: "TOTAL IN CASH DRAWER",
        flujoFecha: "Daily Cash Flow",
        entradaBtn: "Cash In",
        salidaBtn: "Cash Out",
        cerrarTurnoCortarCaja: "Close Shift & Reconcile Cash",
        actividadTurno: "Shift Activity",
        movimientos: "Transactions",
        sinActividad: "No activity yet",
        sinActividadDesc: "Sales and transactions will appear here.",
        historialAuditoriaGlobal: "Global History & Audit",
        buscarHistorial: "Search full history...",
        fechaHoraCompleta: "Date & Time",
        tipoMovimiento: "Type",
        motivoDetalles: "Reason / Details",
        importe: "Amount",
        cierreTurnoAuditoria: "Shift Closure & Audit",
        detalleBtn: "Details",
        noRegistros: "No records found.",
        detallesTurnoPasado: "Past Shift Details",
        fechaHoraCierre: "Closing Date & Time",
        totalAuditado: "Audited Total",
        transaccionesTurno: "Shift Transactions",
        noTransaccionesTurno: "No transactions were recorded in this shift.",
        ingresoCajaTitulo: "Cash In",
        retiroCajaTitulo: "Cash Withdrawal",
        tipFondoCaja: "Tip: If it's to start the shift, include the word \"Float\" in the reason.",
        registrarBtn: "Register",
        alertaMontoInvalido: "Invalid amount.",
        alertaMotivoVacio: "You must specify a reason.",
        alertaEfectivoInsuficiente: "Insufficient cash in drawer for this withdrawal.",
        alertaCajaCero: "The cash drawer is at zero.",
        confirmarCorteLargo: "Are you sure you want to perform the Cash Reconciliation?\n\nThe current shift will be closed, the current cash will become the Cash Float for the next shift, counters will reset to zero, and your detailed ticket will be printed.",
        corteGenerandoTicket: "Cash reconciliation recorded successfully. Generating ticket...",
        alertaCorteAntiguo: "This reconciliation is too old and does not have the compatible format to view the breakdown.",
        alertaErrorTicket: "Could not generate the ticket.",
        fondoInicial: "Initial Float",
        entradas: "Inflows",
        salidas: "Outflows",
        cortesCaja: "Cash Reconciliations",
        totalAlCierre: "Closing Total",
        detalleMovimientos: "MOVEMENT DETAILS",
        ticketCorteTitulo: "Reconciliation Ticket",
        corteCajaTurno: "CASH RECONCILIATION (SHIFT)",
        firmaConformidad: "Acknowledgment Signature",
        documentoAuditoria: "Audit Document",
        generadoAuto: "Automatically generated",
        // Módulo Clientes y Expedientes
        directorioExpedientes: "Clinical Records (Admission)", placeholderBuscarCliente: "🔍 Search by name, phone, CURP or record ID...", 
        nuevoPaciente: "New Patient", expediente: "Record ID", datosGenerales: "Personal Data",
        sexo: "Sex", curp: "CURP", sinCurp: "Reason no CURP", fechaNacimiento: "Date of Birth",
        correo: "Email", domicilio: "Full Address", contactoEmergencia: "Emergency Contact",
        parentesco: "Relationship", responsableLegal: "Legal Guardian (If applies)", idioma: "Preferred Language",
        alertasClinicas: "Clinical Alerts", tipoAlerta: "Alert Type", descripcionAlerta: "Description", gravedad: "Severity",
        alergia: "Allergy", embarazo: "Pregnancy", marcapasos: "Pacemaker/Implant", anticoagulantes: "Anticoagulants",
        enfermedadTransmisible: "Transmissible Disease", riesgoUrgencia: "Risk/Emergency",
        altaPacienteExito: "Record successfully created.", camposObligatorios: "Missing required fields.",
        visitas: "Visits", totalInvertido: "Total Invested", acciones: "Actions", verHistorialCompleto: "View Full History", 
        sinTelefono: "No phone", articulo: "Item", pUnit: "Unit P.", totalTicket: "Ticket Total:", sinRegistrosCompras: "No purchase records found.",
        estadoCivil: "Marital Status",
        soltero: "Single",
        casado: "Married",
        divorciado: "Divorced",
        viudo: "Widowed",
        unionLibre: "Common-Law Union",
        otro: "Other",
        ocupacion: "Occupation",
        ejOcupacion: "E.g. Student, Teacher, Engineer...",
        pacienteHablaIngles: "Patient Speaks English (Direct Access to Physician)",
        notaInterna: "Internal Note (Staff)",
        notaInternaDesc: "Private comments. The patient will not see this.",
        ejNotaInterna: "E.g. Difficult client, prefers to see Dr. Ana...",
        abandonoTx: "Treatment Abandonment",
        alDia: "Up to Date",
        confirmarEliminarExpediente: "Are you sure you want to permanently delete the medical record of",
        accionNoDeshacer: "This action cannot be undone.",
        expedienteEliminadoExito: "Duplicate medical record deleted successfully.",
        errorEliminarExpediente: "Error deleting: This patient likely has associated sales or medical history and cannot be deleted for security reasons. \n\nDetails: ",
        descAlertasClinicas: "These alerts will generate a red visual warning in the patient's medical history.",
        seleccionarAlerta: "-- Select Alert --",
        especificarDetalleAlerta: "Specify alert details...",
        anadirAlerta: "Add Alert",
        guardarExpediente: "Save Medical Record",
        editarExpediente: "Edit Medical Record",
        altaExpedienteClinico: "Create Medical Record",
        expAbrev: "MR:",
        sinCurpAbrev: "No CURP",
        noExpedientes: "No medical records found.",
        inactivoPor: "Inactive for",
        dias: "days",
        anos: "years",
        pacienteYaExiste: "This patient appears to already exist",
        confirmarCrearNuevo: "Are you sure you want to create a new record?",
        errorActualizar: "Error updating: ",
        seleccionar: "Select",
        femenino: "Female",
        masculino: "Male",
        contactoEmergenciaNum: "Emergency Contact",
        // Módulo Escritorio Médico
        escritorioMedico: "Medical Dashboard", historiaClinica: "Medical History", notasEvolucion: "Progress Notes",
        motivoConsulta: "Reason for Consultation", padecimientoActual: "Current Illness", antecedentesFamiliares: "Family History",
        antecedentesPersonales: "Personal Medical History (Pathological)", habitosSustancias: "Habits and Substance Use",
        medicamentosActuales: "Current Medications", ginecoObstetricos: "Gynecological and Obstetric History",
        interrogatorioSistemas: "Review of Systems", exploracionFisica: "Physical Examination and Vital Signs",
        diagnosticoCie: "Diagnosis (ICD) / Clinical Problem", valoracionMtc: "TCM Assessment (Syndrome/Pattern)",
        pronostico: "Prognosis", planTratamiento: "Treatment Plan / Objectives", firmar: "Sign and Close Document",
        documentoFirmado: "Signed and Unalterable Document", evolucion: "Progress (Changes, Pain)",
        evaluacionSignos: "Assessment and Signs", procedimientoTecnica: "Procedure (Points, Technique)",
        materialAgujas: "Materials (Needles, Sterile, Brands)", resultadoTolerancia: "Outcome and Tolerance",
        planIndicaciones: "Plan and Instructions", nuevaNota: "New Progress Note", guardarBorrador: "Save Draft",
        consentimientos: "Informed Consents", adendas: "Addendums (Corrections)", nuevoConsentimiento: "Generate Consent",
        testigo1: "Witness 1 Full Name", testigo2: "Witness 2 Full Name", pacienteAcepta: "The patient understands the risks and accepts the treatment.",
        exportarPdf: "Export Official Record (PDF)", textoLegalAcupuntura: "I authorize Acupuntura China Tradicional HK to perform human acupuncture, electroacupuncture, cupping, and related methods. I understand the benefits and risks (mild pain, bruising, dizziness).",
        firmarConsentimiento: "Sign Official Consent", redactarAdenda: "Write Addendum (Correction)", firmarAdenda: "Sign Addendum",
        avisoPrivacidad: "Accepted Privacy Notice (v1.0)", aceptarAviso: "Mandatory: Patient must accept the Privacy Notice.",
        hojaReferencia: "Generate Transfer/Referral Sheet", motivoTraslado: "Reason for Transfer / Emergency",
        hospitalReceptor: "Receiving Facility", impresionDiagnostica: "Current Diagnostic Impression",
        // Missing keys - Medical Dashboard Module
        misPacientes: "My Patients",
        buscarPaciente: "Search patient...",
        noResultados: "No results found.",
        interrogatorio: "Patient Interview",
        antecedentesHabitos: "Medical History and Habits",
        planificacionFamiliar: "Family Planning Methods",
        antecedentesRenalesPsicologicos: "Renal and Psychological History",
        esferaFisicaMental: "Physical and Mental Health",
        esferaMental: "Mental Health (ADHD, Stress, Depression...)",
        habitosSueno: "Sleep Habits (How does the patient sleep?)",
        diagnosticoMtc: "TCM Diagnosis (Traditional Chinese Medicine)",
        mtcPulsoLengua: "Pulse and Tongue",
        mtcRostroOjos: "Face and Eyes",
        mtcColoresSaboresSonidos: "Colors, Tastes, and Sounds",
        conclusionTratamiento: "Conclusion and Treatment",

        imprimirDiagnostico: "Print Diagnosis",
        resumenSesionImpresion: "Session Summary (For Printing)",
        puntosAcupuntura: "Acupuncture Points Used",
        tiempoRetencion: "Retention Time (Minutes)",
        sesionesRequeridas: "Required Sessions (Suggested)",
        diagnosticoSesion: "Session Diagnosis (Assessment)",

        alertaFaltanCamposHistoria: "To sign, you must fill in at least the Reason for Consultation, Diagnosis, and Treatment Plan.",
        confirmarFirmaHistoria: "Are you sure you want to sign? The document will be locked and legally unalterable.",
        borradorGuardado: "Draft Saved",
        normaFirmaNota: "According to regulations, you cannot sign with empty fields. Describe the progress, procedure, or session diagnosis.",
        confirmarFirmaNota: "Are you sure you want to sign this note? It cannot be deleted or altered.",
        alertaSinDiagnostico: "There is no session diagnosis available to print.",

        alertaCamposMinimos: "Name, Phone, Date of Birth, and Sex are required.",
        errorRegistrar: "Registration error: ",
        expedienteCreadoExito: "Medical record created successfully.",

        alertaAdendaCorta: "The addendum must be clear and properly justified.",
        confirmarFirmaAdenda: "Are you sure you want to sign and attach this addendum to the medical record?",
        adendaFirmadaExito: "Addendum signed and attached successfully.",

        alertaTestigos: "The names of two legal witnesses are required.",
        alertaAceptarTerminos: "The patient must accept the terms by checking the box.",
        confirmarConsentimientoLegal: "By signing, the informed consent will be legally registered in the name of the patient and witnesses.",
        consentimientoGeneradoExito: "Official informed consent generated and signed successfully.",

        alertaDatosTraslado: "You must complete all transfer information.",

        seleccionarOCrearNota: "Select or create a note",
        historialEvolucionClinica: "The clinical progress history will appear here.",

        consentimientosVacios: "No informed consents have been recorded in this medical record.",
        consentimientoOficial: "Official Informed Consent",

        escritorioClinico: "Clinical Dashboard",
        seleccionarPacienteDirectorio: "Select a patient from the directory on the left to begin.",

        altaRapida: "Quick Registration",
        camposMinimosNorma: "Minimum fields required by regulation. Reception can complete the remaining information later.",
        nombreCompleto: "Full Name",
        telefono: "Phone",
        fechaNacimiento: "Date of Birth",
        sexo: "Sex",
        crearExpediente: "Create Medical Record",

        generarHojaReferencia: "Generate Referral Form",
        documentoReferenciaDescripcion: "This official document authorizes the transfer or referral of the patient to another hospital for emergency care or medical studies.",
        generarDocumento: "Generate Document",

        imprimirRecetaDiagnostico: "Print Prescription/Diagnosis for Patient",
        escribeCorreccion: "Write the correction or erratum here...",
        firmadaPor: "Signed by",
        cancelar: "Cancel",

        // PDF - Assessment
        dictamenEvaluacionSeguimiento: "Evaluation and Follow-up Assessment",
        paciente: "Patient:",
        fecha: "Date:",
        expediente: "Medical Record:",
        terapeuta: "Therapist:",
        diagnosticoEvaluacionClinica: "Diagnosis / Clinical Assessment:",
        pronosticoTratamientoSugerido: "Prognosis and Suggested Treatment:",
        sesionesSeguimiento: "Follow-up sessions are recommended:",
        sesionesParaObservarEvolucion: "sessions to monitor progress.",
        indicacionesCasa: "Home Care Instructions:",
        firmaTerapeuta: "Therapist Signature",

        // PDF - Medical Record
        expedienteClinico: "Medical Record",
        expedienteClinicoOficial: "Official Medical Record (NOM-004-SSA3-2012 Compliance)",
        identificacionPaciente: "PATIENT IDENTIFICATION",
        nombre: "Name:",
        curp: "CURP:",
        noProporcionado: "Not provided",
        sexoTelefono: "Sex / Phone:",
        alertasClinicas: "CLINICAL ALERTS",
        historiaClinicaInicial: "INITIAL MEDICAL HISTORY",
        motivoConsultaPdf: "Reason for Consultation:",
        diagnosticoCiePdf: "Diagnosis (ICD):",
        planTratamientoPdf: "Treatment Plan:",
        firmadoPor: "SIGNED BY:",

        // PDF - Referral
        hojaReferenciaTrasladoMedico: "MEDICAL REFERRAL AND TRANSFER FORM",
        establecimientoReceptorPdf: "Receiving Facility:",
        fechaHoraEmision: "Date and Time of Issue:",
        datosPaciente: "PATIENT INFORMATION",
        nombrePaciente: "Patient Name:",
        expedienteCurp: "Medical Record / CURP:",
        edadSexo: "Age / Sex:",
        resumenClinicoMotivoEnvio: "CLINICAL SUMMARY AND REASON FOR REFERRAL",
        impresionDiagnosticaPdf: "Diagnostic Impression:",
        motivoReferenciaUrgencia: "Reason for Referral / Emergency:",
        medicoTratante: "Attending Physician",
        nombreFirmaMedico: "Physician Name and Signature",
    },
    zh: {
        // Generales y Sidebar
        panelControl: "控制面板", puntoVenta: "销售终端", inventario: "库存", 
        promociones: "促销", reportes: "报告", clientes: "客户", configuracion: "设置", 
        cerrarSesion: "登出", enLinea: "在线", sucursal: "分店", todas: "全部",
        // Módulo Ventas
        buscar: "搜索", producto: "产品", tipoPrecio: "价格类型", unitario: "单价", 
        cantidadAbrev: "数量", importeNeto: "净额", esperandoLecturas: "等待扫描...", 
        anadirRapido: "快速添加", verCatalogo: "查看完整目录", subtotal: "小计:", 
        descuentos: "折扣:", asignarPaciente: "分配患者:", publicoGeneral: "-- 普通大众 --", 
        formaPago: "付款方式:", efectivo: "现金", tarjeta: "刷卡", transferencia: "转账", total: "总计:", 
        cobrar: "收费", catalogoProductos: "产品目录", buscarNombreCodigo: "🔍 按名称或代码搜索...", 
        codigo: "代码", nombre: "名称", precio: "价格", agregar: "添加", 
        registrarPaciente: "快速注册患者", nombreCompleto: "全名", telefono: "电话", 
        guardarSeleccionar: "保存并选择", cancelar: "取消", 
        placeholderEscanear: "[准备扫描] 刷条形码...", procesando: "处理中...", 
        carritoVacio: "购物车为空。", cobradoExito: "收费成功:", general: "常规", mayoreo: "批发", distribuidor: "经销商", precioMedico: "医疗价格",
        folioTransferencia: "转账参考号", ingresaFolio: "例: 987654321", debito: "借记卡", credito: "信用卡", 
        tipoTarjeta: "卡类型", historialDia: "今日销售记录", vendedor: "收银员", hora: "时间", 
        articulos: "物品", folioRequerido: "必须输入转账参考号。",
        cajaFinanzas: "现金与财务", consumosMedicos: "医疗用品", promociones: "促销活动", cerrarSesion: "登出",notasVentaOpcional: "添加销售备注（可选）",
        // TRADUCCIONES MÓDULO FINANZAS
        comparativasGrales: "对比与图表",
        tabSucursales: "分店对比",
        tabDoctores: "医生生产力",
        comparativaSucursales: "分店对比分析",
        sucursal: "分店",
        totalVentas: "总销售额",
        consultas: "诊疗",
        productos: "产品",
        ticketsTotales: "已发凭票数",
        ticketPromedio: "平均客单价",
        topProductos: "热销产品前三",
        comparativaDoctores: "医生绩效与生产力",
        doctor: "医生",
        consultasAtendidas: "已接诊数",
        ingresoGenerado: "产生收入",
        retencionPacientes: "患者留存率",
        indiceRetencion: "留存指数",
        pacientesUnicos: "独立患者数",
        sinDatosDoctores: "此期间没有分配给医生的诊疗记录。",
        sinDatosSucursales: "此期间没有销售记录可供比较。",
        acupuntura: "针灸",
        huanqiu: "环球",
        consultasAcupuntura: "诊疗（针灸）",
        prodHuanqiu: "产品（环球）",
        totalConsultasRealizadas: "已完成诊疗",
        subtotalEfectivo: "现金小计",
        subtotalTarjeta: "银行卡小计",
        subtotalTransferencia: "转账小计",
        ticketCorteAuditoria: "现金清账与审计",
        detalleMovimientos: "交易明细",
        firmaConformidad: "确认签字",
        documentoAuditoria: "审计文件",
        generadoAuto: "自动生成",
        movimientosFinanzas: "财务报告",
        ventaEfectivoAbrev: "现金销售",
        reporteDiario: "日报",
        reportePeriodo: "周期",
        vistaSucursal: "分店视图",
        vistaGlobal: "全局视图",
        fechaGeneral: "通用日期",
        desde: "从",
        hasta: "到",
        exportarExcel: "导出Excel",
        imprimirReporte: "打印报告",
        analizandoFinanzas: "正在分析财务...",
        cajaFisica: "实体钱箱",
        enVivo: "实时",
        fondoInicial: "初始备用金",
        ventasEfectivoAbrev: "现金销售（现金）",
        entradas: "入账",
        salidas: "出账",
        fondoCajaBtn: "备用金",
        entradaBtn: "入账",
        salidaBtn: "出账",
        corteCajaBtn: "结算",
        clinicaOficial: "官方诊所",
        extrasProd: "附加项/产品",
        granTotalVentas: "总销售额",
        efectivoLabel: "现金",
        tarjetaLabel: "银行卡",
        transferenciaLabel: "转账",
        efectivoTotal: "现金总计",
        tarjetaTotal: "银行卡总计",
        transfTotal: "转账总计",
        tabConsultas: "诊疗",
        tabExtras: "产品与附加项",
        tabAuditoria: "现金审计",
        folio: "凭证号",
        fecha: "日期",
        sucursalEmisora: "分店",
        clientes: "客户",
        servicioClinico: "诊疗服务",
        productoExtra: "产品/附加项",
        cantidadAbrev: "数量",
        metPago: "支付方式",
        importe: "金额",
        sinDatosClinica: "未找到诊所销售记录。",
        sinDatosExtras: "未找到附加销售记录。",
        fechaHoraCompleta: "日期和时间",
        tipoMovimiento: "类型",
        motivoDetalles: "原因/详情",
        ticketBtn: "凭票",
        cierreTurnoAuditoria: "班次结算与审计",
        detalleBtn: "详情",
        reimprimirBtn: "重印",
        sinDatosCaja: "未找到现金流水记录。",
        establecerFondoCaja: "设置备用金",
        ingresoCajaTitulo: "现金存入",
        retiroCajaTitulo: "现金提取",
        tipFondoCaja: "提示：如果用于开启班次，请在原因中包含“备用金”字样。",
        montoEfectivoDesc: "现金金额（$）",
        motivoDescripcion: "原因/描述",
        cancelar: "取消",
        procesar: "处理",
        registrarBtn: "登记",
        alertaMontoInvalido: "金额无效。",
        alertaMotivoVacio: "请指定原因。",
        alertaEfectivoInsuficiente: "现金不足，无法提取此金额。",
        alertaCajaCero: "现金余额为零，无可结算的现金。",
        confirmarCorteLargo: "确认进行现金清账吗？\n\n系统将提取所有现金，使余额归零，并生成审计凭票。\n\n（您需要在下一个班次手动输入初始备用金）。",
        corteExitoso: "清账成功。当前现金余额为$0.00。",
        reporteFinancieroDoc: "香港针灸财务报告",
        generadoAuto: "由系统自动生成",
        detallesTurnoPasado: "历史班次详情",
        fechaHoraCierre: "结算日期和时间",
        totalAuditado: "审计总额",
        transaccionesTurno: "班次交易记录",
        noTransaccionesTurno: "此班次无交易记录。",
        // Módulo Inventario
        catalogo: "目录", familiasGrupos: "系列 / 分组", kardex: "出入库记录 (Kardex)", nuevoProducto: "新物品", 
        familia: "系列", stock: "库存量", ajustar: "调整", suelto: "单个", familiasAgrupaciones: "系列和分组", 
        crearFamilia: "创建系列", id: "编号", nombreFamilia: "系列名称", accionesFamilia: "操作", 
        editarIntegrantes: "编辑成员", fijarPrecioMasivo: "批量定价", noFamiliasCreadas: "尚未创建系列。", 
        kardexAuditoria: "审计记录", fecha: "日期", movimiento: "动态", cantidad: "数量", motivo: "原因", 
        editarFamilia: "编辑系列", nuevaFamilia: "新系列", labelNombreFamilia: "系列名称", 
        ejemploFamilia: "例：钢针", seleccionaProductosFamilia: "选择属于此系列的产品：", 
        guardarFamilia: "保存系列", nuevoArticulo: "新物品", familiaOpcional: "系列 (可选)", 
        sinGrupo: "-- 无分组 (单个) --", codigoBarras: "条形码", nombreArticulo: "物品名称", 
        preciosInstruccion: "价格 (留空则复制常规价格)", generalReq: "常规 *", guardarArticulo: "保存物品", 
        cantidadInvalida: "数量无效", stockActualizado: "库存已更新。", preciosInvalidos: "价格无效。", 
        preciosActualizadosGlobal: "所有分店的价格已更新。", promptPrecioMasivo1: "请输入该系列所有物品的新常规价格", 
        promptPrecioMasivo2: "批发、经销商和医疗价格将与此一致。", preciosMasivosAplicados: "批量价格已成功应用于所有系列成员。", 
        nombreFamiliaObligatorio: "系列名称必填。", faltanCampos: "缺少必填字段。", familiaGuardadaExito: "保存成功。",
        editar: "编辑", eliminar: "删除", confirmarEliminarProducto: "您确定要删除此项目吗？它将从目录中隐藏，但保留在报告历史中。",
        tipoArticulo: "物品类型", productoFisico: "实体产品 (使用库存)", servicioInfinito: "服务 (无限库存)",
        infinito: "无限", productoEliminadoExito: "项目已从目录中移除。", productoActualizadoExito: "项目已成功更新。", editarArticulo: "编辑物品",
        inventarioGlobal: "全局库存", transferir: "转移", transferenciaInventario: "库存转移", 
        sucursalDestino: "目标分店", cantidadTransferir: "转移数量", motivoOpcional: "原因 (可选)", 
        confirmarTransferencia: "确认转移", transferenciaExitosa: "转移成功完成。", 
        errorTransferencia: "转移错误: ", seleccionaDestino: "选择目标分店。", 
        totalGlobal: "全局总计", exportarKardex: "导出记录 (CSV)", imprimirPdf: "打印 PDF",
        estrategiaPrecio: "定价策略", descPrecioSucursal: "该产品将在各分店使用不同的价格。", descPrecioGlobal: "所有分店价格相同 (全局)。", 
        preciosDiferenciados: "📍 差异化价格 (仅限此分店)", preciosGlobales: "🌎 使用共享的全局价格", 
        tooltipPrecioSucursal: "此分店的固定价格", tooltipPrecioGlobal: "共享全局价格", 
        ajusteStock: "调整 (+/-)", guardarRenglon: "保存行", errorStockNegativo: "调整导致库存为负。", 
        preciosActualizadosLocal: "价格已更新 (仅限此分店)", cambiosGuardados: "更改保存成功。", 
        placeholderAjuste: "+0 / -0", aplicaGlobal: "(全局适用)",
        buscarArticulo: "按名称、代码或系列搜索...",
        esConsultaMedica: "在报告中计为'医疗咨询'",
        consultaMedicaBadge: "医疗咨询",
        // Módulo Promociones
        llenaCampos: "请填写必填字段。", seleccionaProductoAlert: "请选择一个产品。", seleccionaFamiliaAlert: "请选择一个系列。", 
        errorCrear: "创建错误: ", campanaLanzada: "活动成功发布。", confirmarBajaCampana: "您要取消此活动吗？", 
        panelPromociones: "促销面板", crearCampana: "创建活动", campana: "活动", aplicaA: "适用于", 
        mecanica: "机制", vigencia: "有效期", estado: "状态", precioFijo: "固定价格", lleva: "买", 
        gratis: "赠", familiaDosPuntos: "系列: ", productoDosPuntos: "产品: ", vigente: "生效中", 
        inactiva: "未生效", nuevaPromocion: "新促销", porProducto: "按产品", porFamilia: "按系列 (分组)", 
        seleccionaProducto: "-- 选择产品 --", seleccionaFamilia: "-- 选择系列 --", 
        nombrePromocionEjemplo: "名称 (例：钢针买二送一)", esquemaDescuento: "折扣方案:", porcentaje: "百分比 (%)", 
        porVolumen: "按数量 (例：买二送一)", llevaTotal: "购买 (总件数):", ej3: "例: 3", descuentaGratis: "折扣 (免费):", 
        ej1: "例: 1", valorDescuento: "折扣值", inicio: "开始:", fin: "结束:", lanzarOferta: "发布优惠",
        // Módulo Reportes Avanzados
        noDatosExportar: "所选范围内没有可导出的数据。", folio: "单号", fechaHora: "日期/时间", 
        sucursalEmisora: "分店", montoCobrado: "收费金额", cierreCaja: "结算_报表", fechaInicio: "开始日期:", 
        fechaFin: "结束日期:", excelCsv: "导出到 Excel", procesandoNube: "正在云端处理交易...", 
        ingresosTotales: "总收入", consultasTotales: "总服务量", insumosDesplazados: "售出产品", 
        ticketPromedio: "客单价", finanzasSucursal: "各分店财务", napoles: "Napoles (那不勒斯)", obrera: "Obrera (奥夫雷拉)", 
        pedregal: "Pedregal (佩德雷加尔)", top5Vendidos: "最畅销前五名", detalle: "明细", uds: "件", sinDatos: "无数据。", 
        auditoriaTransacciones: "近期交易审计", noMovimientos: "在所选时间范围内未检测到任何交易。", 
        articuloEliminado: "已删除物品", desgloseFinanciero: "按分店财务明细", ingresosConsultas: "服务收入", 
        ingresosProductos: "产品收入", participacion: "份额",
        reporteDiario: "日报", reportePeriodo: "按时间段", vistaSucursal: "我的分店", vistaGlobal: "全局 (所有)",
        empresaA: "咨询 (服务)", empresaB: "附加产品 (库存)", ingresosA: "咨询收入", ingresosB: "产品收入",
        buscarReporte: "按患者或物品过滤...", granTotal: "总计", metPago: "付款方式",
        efectivoLabel: "现金:", tarjetaLabel: "刷卡:", transferenciaLabel: "转账:",
        efectivoTotal: "总现金:", tarjetaTotal: "总刷卡:", transfTotal: "总转账:",
        resumenGlobal: "全局摘要 (两家公司)", granTotalLabel: "总计:",
        totalEfectivo: "总现金:", totalTarjetas: "总刷卡:", totalTransferencias: "总转账:",
        totalConsultas: "总咨询:", total产品: "总产品:",
        excelEfectivo: "> 现金:", excelTarjetas: "> 刷卡:", excelTransferencias: "> 转账:",
        // Módulo Configuración y Usuarios
        gestionUsuariosPermisos: "用户与权限管理", registrarEmpleado: "注册员工", cargandoPersonal: "正在加载员工...", 
        empleado: "员工", rolPrincipal: "主要角色", clinica: "诊所", permisosAccesoModulos: "模块访问权限 (视图)", 
        activo: "活跃", suspendido: "已暂停", recepcionista: "前台收银", gerente: "经理", adminGlobal: "全局管理员", 
        todasGlobal: "全部 (全局)", accesoRestringido: "访问受限", soloAdminConfig: "只有管理员可以管理系统设置。", 
        altaNuevoEmpleado: "注册新员工", correoLogin: "电子邮箱 (用于登录)", contrasenaTemporal: "临时密码", 
        rol: "角色", clinicaAsignada: "分配诊所", crearCuenta: "创建账户", errorCrearUsuario: "创建用户错误: ", 
        usuarioCreadoExito: "用户创建成功。请重新以管理员身份登录。",
        errorActualizandoPermisos: "更新权限错误: ",
        // Módulo Consumos Médicos y Terapeutas (NUEVAS LLAVES)
        insumosMedicos: "医疗用品", registroConsumo: "出库登记", directorioDoctores: "医生目录",
        reportesConsumo: "消耗报告", seleccionaDoctor: "-- 选择医生 --", registrarSalida: "确认出库",
        nuevoDoctor: "新医生", especialidad: "专业", crearDoctor: "注册医生",
        historialDoctores: "医生消耗历史记录", reporteMensual: "月度报告",
        articulosEntregados: "已交付物品", consumoRegistrado: "消耗已登记，库存已成功扣除。",
        stockInsuficiente: "库存不足！仅剩", unidadesDe: "件", enLugar: "在", 
        codigoNoRegistrado: "此分店未注册代码：", limiteAlcanzado: "达到上限：仅有", 
        disponibles: "可用。", atencion: "注意：", error: "错误：", agregaInsumos: "添加用品以登记出库。",
        marcaEstrella: "在库存中标记星号以将用品固定于此。", disp: "可用", verCatalogoCompleto: "查看完整目录",
        terapeutaAsignado: "指定治疗师", seleccionaQuienRetira: "选择领用人", accionDescontaraInventario: "此操作将扣除以下分店的库存：",
        noGeneraraIngresos: "但不会产生财务收入。", directorioTerapeutas: "治疗师目录", nuevoTerapeuta: "新治疗师",
        inactivo: "停用", noDoctores: "没有注册医生。", historialSalidas: "出库历史记录", filtrarTerapeuta: "按治疗师筛选",
        todosTerapeutas: "所有治疗师", materialRetirado: "领用材料", noSalidas: "此期间未找到出库记录。",
        registrarTerapeuta: "注册治疗师", ejAcupunturista: "例：针灸师", opcional: "选填", guardar: "保存",
        catalogoInsumos: "用品目录", anadir: "添加", noInsumo: "未找到用品。",
        // Módulo Caja
        flujoCaja: "收银机", saldoActual: "收银机现金", montoRecibido: "收到现金:", 
        cambio: "找零", montoInsuficiente: "收到的金额小于应付总额。",
        ingresarEfectivo: "存入现金", retirarEfectivo: "提取现金", hacerCorte: "结算收银机 (Corte)",
        movimientosHoy: "今日流水", tipoMovimiento: "类型", ingresoManual: "手动存入",
        retiroManual: "手动提取", ventaEfectivo: "销售 (现金)", corteDeCaja: "收银结算",
        motivo: "原因 / 备注", confirmarCorte: "您确定要结算吗？所有现金将被提取，余额将归零 ($0.00)",
        corteExitoso: "收银结算成功，请妥善保管现金。",
        estadoCivil: "婚姻状况",
        soltero: "未婚",
        casado: "已婚",
        divorciado: "离婚",
        viudo: "丧偶",
        unionLibre: "同居关系",
        otro: "其他",
        ocupacion: "职业",
        ejOcupacion: "例如：学生、教师、工程师……",
        pacienteHablaIngles: "患者会说英语（直接转诊至医生）",
        notaInterna: "内部备注（工作人员）",
        notaInternaDesc: "私人备注。患者无法查看此内容。",
        ejNotaInterna: "例如：难以沟通的客户，偏好由安娜医生接诊……",
        abandonoTx: "放弃治疗",
        alDia: "按时治疗",
        confirmarEliminarExpediente: "您确定要永久删除患者的病历吗？",
        accionNoDeshacer: "此操作无法撤销。",
        expedienteEliminadoExito: "重复病历已成功删除。",
        errorEliminarExpediente: "删除错误：该患者可能已有相关销售记录或病历，为安全起见无法删除。\n\n详情：",
        descAlertasClinicas: "这些警报将在患者病历中生成红色视觉警示。",
        seleccionarAlerta: "-- 选择警报 --",
        especificarDetalleAlerta: "填写警报详细信息……",
        anadirAlerta: "添加警报",
        guardarExpediente: "保存病历",
        editarExpediente: "编辑病历",
        altaExpedienteClinico: "创建病历",
        expAbrev: "病历：",
        sinCurpAbrev: "无 CURP",
        noExpedientes: "未找到病历。",
        inactivoPor: "已停用",
        dias: "天",
        anos: "年",
        pacienteYaExiste: "该患者似乎已经存在",
        confirmarCrearNuevo: "您确定要创建新记录吗？",
        errorActualizar: "更新错误：",
        seleccionar: "选择",
        femenino: "女性",
        masculino: "男性",
        contactoEmergenciaNum: "緊急聯絡人",
        efectivoActualCaja: "当前现金余额",
        desgloseTurnoActual: "当前班次明细",
        fondoCaja: "备用金",
        ventasEfectivoAbrev: "现金销售额",
        entradasManuales: "手动入账",
        salidasRetiros: "支出 / 提款",
        totalEnCaja: "现金总额",
        flujoFecha: "当日流水",
        entradaBtn: "入账",
        salidaBtn: "出账",
        cerrarTurnoCortarCaja: "结束班次并结算清账",
        actividadTurno: "班次活动",
        movimientos: "交易流水",
        sinActividad: "暂无活动",
        sinActividadDesc: "销售和交易流水将显示在此处。",
        historialAuditoriaGlobal: "全局历史与审计",
        buscarHistorial: "搜索完整历史记录...",
        fechaHoraCompleta: "日期和时间",
        tipoMovimiento: "交易类型",
        motivoDetalles: "原因 / 详情",
        importe: "金额",
        cierreTurnoAuditoria: "班次结算与审计",
        detalleBtn: "详情",
        noRegistros: "未找到记录。",
        detallesTurnoPasado: "历史班次详情",
        fechaHoraCierre: "结算日期和时间",
        totalAuditado: "审计总额",
        transaccionesTurno: "班次交易记录",
        noTransaccionesTurno: "此班次无交易记录。",
        ingresoCajaTitulo: "现金入账",
        retiroCajaTitulo: "现金提取",
        tipFondoCaja: "提示：如果用于开启班次，请在原因中包含“备用金”字样。",
        registrarBtn: "登记",
        alertaMontoInvalido: "金额无效。",
        alertaMotivoVacio: "请指定原因。",
        alertaEfectivoInsuficiente: "现金不足，无法提取此金额。",
        alertaCajaCero: "现金余额为零。",
        confirmarCorteLargo: "确认进行清账结算吗？\n\n当前班次将结束，当前现金余额将转为下个班次的备用金，计数器将归零，并打印您的详细凭票。",
        corteGenerandoTicket: "清账结算成功。正在生成凭票...",
        alertaCorteAntiguo: "此结算记录太旧，不具备兼容格式以查看明细。",
        alertaErrorTicket: "无法生成凭票。",
        fondoInicial: "初始备用金",
        entradas: "入账",
        salidas: "出账",
        cortesCaja: "清账记录",
        totalAlCierre: "期末总额",
        detalleMovimientos: "交易明细",
        ticketCorteTitulo: "结算凭票",
        corteCajaTurno: "现金清账（班次）",
        firmaConformidad: "确认签字",
        documentoAuditoria: "审计文件",
        generadoAuto: "自动生成",
        // Módulo Clientes y Expedientes
        directorioExpedientes: "临床档案 (入院)", placeholderBuscarCliente: "🔍 按姓名、电话、CURP或档案号搜索...", 
        nuevoPaciente: "新患者", expediente: "档案号", datosGenerales: "个人资料",
        sexo: "性别", curp: "CURP (身份证)", sinCurp: "无CURP原因", fechaNacimiento: "出生日期",
        correo: "电子邮件", domicilio: "详细地址", contactoEmergencia: "紧急联系人",
        parentesco: "关系", responsableLegal: "法定监护人 (如适用)", idioma: "首选语言",
        alertasClinicas: "临床警告", tipoAlerta: "警告类型", descripcionAlerta: "描述", gravedad: "严重程度",
        alergia: "过敏", embarazo: "怀孕", marcapasos: "起搏器/植入物", anticoagulantes: "抗凝剂",
        enfermedadTransmisible: "传染病", riesgoUrgencia: "风险/紧急情况",
        altaPacienteExito: "档案创建成功。", camposObligatorios: "缺少必填字段。",
        visitas: "访问次数", totalInvertido: "总消费", acciones: "操作", verHistorialCompleto: "查看完整历史", 
        sinTelefono: "无电话", articulo: "物品", pUnit: "单价", totalTicket: "账单总计:", sinRegistrosCompras: "没有购买记录。",
        // Módulo Escritorio Médico
        escritorioMedico: "医疗工作台", historiaClinica: "病历", notasEvolucion: "病情进展记录",
        motivoConsulta: "就诊原因", padecimientoActual: "现病史", antecedentesFamiliares: "家族病史",
        antecedentesPersonales: "个人病史（病理）", habitosSustancias: "生活习惯及物质使用",
        medicamentosActuales: "当前用药", ginecoObstetricos: "妇科及产科病史",
        interrogatorioSistemas: "系统回顾", exploracionFisica: "体格检查及生命体征",
        diagnosticoCie: "诊断（ICD）/ 临床问题", valoracionMtc: "中医评估（证候/证型）",
        pronostico: "预后", planTratamiento: "治疗计划 / 目标", firmar: "签名并关闭文档",
        documentoFirmado: "已签署且不可更改的文档", evolucion: "病情进展（变化、疼痛）",
        evaluacionSignos: "评估及体征", procedimientoTecnica: "操作（穴位、技术）",
        materialAgujas: "材料（针具、无菌用品、品牌）", resultadoTolerancia: "结果及耐受性",
        planIndicaciones: "计划及医嘱", nuevaNota: "新建病情进展记录", guardarBorrador: "保存草稿",
        consentimientos: "知情同意书", adendas: "补充记录 (更正)", nuevoConsentimiento: "生成同意书",
        testigo1: "证人 1 全名", testigo2: "证人 2 全名", pacienteAcepta: "患者了解风险并接受治疗。",
        exportarPdf: "导出官方档案 (PDF)", textoLegalAcupuntura: "我授权 Acupuntura China Tradicional HK 对我进行人体针灸、电针、拔罐及相关方法的治疗。我了解其益处及风险（轻微疼痛、瘀伤、头晕）。",
        firmarConsentimiento: "签署正式同意书", redactarAdenda: "撰写补充记录 (更正)", firmarAdenda: "签署补充记录",
        avisoPrivacidad: "已接受隐私声明（v1.0）", aceptarAviso: "必填：患者必须接受隐私声明。",
        hojaReferencia: "生成转诊单（转院）", motivoTraslado: "转院原因 / 紧急情况",
        hospitalReceptor: "接收医疗机构", impresionDiagnostica: "当前诊断印象",
        // Claves faltantes - Módulo Escritorio Médico
        misPacientes: "我的患者",
        buscarPaciente: "搜索患者……",
        noResultados: "未找到结果。",
        interrogatorio: "问诊",
        antecedentesHabitos: "病史及生活习惯",
        planificacionFamiliar: "计划生育方式",
        antecedentesRenalesPsicologicos: "肾脏及心理病史",
        esferaFisicaMental: "身心状况",
        esferaMental: "心理状况（多动症、压力、抑郁……）",
        habitosSueno: "睡眠习惯（睡眠情况）",
        diagnosticoMtc: "中医诊断（传统中医）",
        mtcPulsoLengua: "脉象与舌象",
        mtcRostroOjos: "面部与眼睛",
        mtcColoresSaboresSonidos: "色、味与声音",
        conclusionTratamiento: "结论与治疗方案",

        imprimirDiagnostico: "打印诊断报告",
        resumenSesionImpresion: "治疗记录摘要（用于打印）",
        puntosAcupuntura: "使用的针灸穴位",
        tiempoRetencion: "留针时间（分钟）",
        sesionesRequeridas: "建议治疗次数",
        diagnosticoSesion: "本次治疗诊断（评估）",

        alertaFaltanCamposHistoria: "签署前，至少需要填写就诊原因、诊断和治疗方案。",
        confirmarFirmaHistoria: "确定要签署吗？签署后，该文件将依法锁定且不可更改。",
        borradorGuardado: "草稿已保存",
        normaFirmaNota: "根据规定，不能在字段为空的情况下签署。请描述病情进展、操作过程或本次治疗诊断。",
        confirmarFirmaNota: "确定要签署此记录吗？签署后将无法删除或修改。",
        alertaSinDiagnostico: "没有可供打印的本次治疗诊断。",

        alertaCamposMinimos: "姓名、电话、出生日期和性别为必填项。",
        errorRegistrar: "登记错误：",
        expedienteCreadoExito: "病历创建成功。",

        alertaAdendaCorta: "补充记录必须清晰且有合理依据。",
        confirmarFirmaAdenda: "确定要签署并将此补充记录添加至病历吗？",
        adendaFirmadaExito: "补充记录已成功签署并添加。",

        alertaTestigos: "需要填写两名法定见证人的姓名。",
        alertaAceptarTerminos: "患者必须勾选复选框以接受相关条款。",
        confirmarConsentimientoLegal: "签署后，该知情同意书将依法登记在患者及见证人名下。",
        consentimientoGeneradoExito: "正式知情同意书已生成并签署。",

        alertaDatosTraslado: "请填写所有转院信息。",

        seleccionarOCrearNota: "请选择或创建一条记录",
        historialEvolucionClinica: "患者的临床病情进展记录将显示在此处。",

        consentimientosVacios: "此病历中尚未登记任何知情同意书。",
        consentimientoOficial: "正式知情同意书",

        escritorioClinico: "临床工作台",
        seleccionarPacienteDirectorio: "请选择左侧患者目录中的患者以开始。",

        altaRapida: "快速登记",
        camposMinimosNorma: "根据规定所需的最少信息。接待人员可以稍后补充其余信息。",
        nombreCompleto: "全名",
        telefono: "电话",
        fechaNacimiento: "出生日期",
        sexo: "性别",
        crearExpediente: "创建病历",

        generarHojaReferencia: "生成转诊单",
        documentoReferenciaDescripcion: "此正式文件用于授权将患者转送或转诊至其他医院接受急诊治疗或医疗检查。",
        generarDocumento: "生成文件",

        imprimirRecetaDiagnostico: "为患者打印处方/诊断报告",
        escribeCorreccion: "请在此填写勘误或更正内容……",
        firmadaPor: "签署人",
        cancelar: "取消",

        // PDF - Dictamen
        dictamenEvaluacionSeguimiento: "评估与随访意见",
        paciente: "患者：",
        fecha: "日期：",
        expediente: "病历号：",
        terapeuta: "治疗师：",
        diagnosticoEvaluacionClinica: "诊断 / 临床评估：",
        pronosticoTratamientoSugerido: "预后及建议治疗方案：",
        sesionesSeguimiento: "建议进行",
        sesionesParaObservarEvolucion: "次随访治疗以观察病情进展。",
        indicacionesCasa: "居家注意事项：",
        firmaTerapeuta: "治疗师签名",

        // PDF - Expediente
        expedienteClinico: "病历",
        expedienteClinicoOficial: "正式病历（符合 NOM-004-SSA3-2012）",
        identificacionPaciente: "患者身份信息",
        nombre: "姓名：",
        curp: "CURP：",
        noProporcionado: "未提供",
        sexoTelefono: "性别 / 电话：",
        alertasClinicas: "临床警示",
        historiaClinicaInicial: "初始病史",
        motivoConsultaPdf: "就诊原因：",
        diagnosticoCiePdf: "诊断（ICD）：",
        planTratamientoPdf: "治疗方案：",
        firmadoPor: "签署人：",

        // PDF - Referencia
        hojaReferenciaTrasladoMedico: "医疗转诊及转院单",
        establecimientoReceptorPdf: "接收医疗机构：",
        fechaHoraEmision: "签发日期及时间：",
        datosPaciente: "患者信息",
        nombrePaciente: "患者姓名：",
        expedienteCurp: "病历号 / CURP：",
        edadSexo: "年龄 / 性别：",
        resumenClinicoMotivoEnvio: "临床摘要及转诊原因",
        impresionDiagnosticaPdf: "诊断印象：",
        motivoReferenciaUrgencia: "转诊原因 / 紧急情况：",
        medicoTratante: "主治医生",
        nombreFirmaMedico: "医生姓名及签名",
    }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState('es');
    const t = (key) => translations[language][key] || key;

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);